// // Generated by Grafana k6 Studio (1.7.0) on 2025-09-16T04:42:25.963Z

// import { group, sleep, check } from "k6";
// import http from "k6/http";
// import execution from "k6/execution";

// export const options = {
//   stages: [
//     { target: 1, duration: "5s" },
//     { target: 10, duration: "20s" },
//     { target: 0, duration: "5s" },
//   ],
//   thresholds: {
//     http_req_duration: ['p(95)<1000'], // 95% requests < 1s
//     http_req_failed: ['rate<0.01'],    // <1% errors allowed
//   },
// };  

// export default function () {
//   let params;
//   let resp;
//   let match;
//   let regex;
//   let url;
//   const correlation_vars = {};

//   group("Default group", function () {
//     params = {
//       headers: {
//         "Proxy-Connection": `keep-alive`,
//         "Upgrade-Insecure-Requests": `1`,
//         Accept: `text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7`,
//         "Accept-Encoding": `gzip, deflate`,
//         "Accept-Language": `en-US,en;q=0.9`,
//       },
//       cookies: {},
//     };

//     url = http.url`http://lccfr-v2-alb-1240804052.us-east-2.elb.amazonaws.com/en/login`;
//     resp = http.request("GET", url, null, params);

//     check(resp, { "status equals 200": (r) => r.status === 200 });

//     params = {
//       headers: {
//         "Proxy-Connection": `keep-alive`,
//         accept: `application/json`,
//         "content-type": `application/json`,
//         Origin: `http://lccfr-v2-alb-1240804052.us-east-2.elb.amazonaws.com`,
//         Referer: `http://lccfr-v2-alb-1240804052.us-east-2.elb.amazonaws.com/en/login`,
//         "Accept-Encoding": `gzip, deflate`,
//         "Accept-Language": `en-US,en;q=0.9`,
//       },
//       cookies: {},
//     };

//     url = http.url`http://3.132.157.35:8080/api/login`;
//     resp = http.request(
//       "POST",
//       url,
//       `{"Email":"harvey@lna.com","Password":"lansa"}`,
//       params,
//     );

//     check(resp, { "status equals 200": (r) => r.status === 200 });

//     params = {
//       headers: {
//         "Proxy-Connection": `keep-alive`,
//         accept: `application/json`,
//         "content-type": `application/json`,
//         Referer: `http://lccfr-v2-alb-1240804052.us-east-2.elb.amazonaws.com/en/accounts`,
//         "Accept-Encoding": `gzip, deflate`,
//         "Accept-Language": `en-US,en;q=0.9`,
//       },
//       cookies: {},
//     };

//     check(resp, { "status equals 200": (r) => r.status === 200 });
//   });
//   sleep(1);
// }

// tests/performance/load-test.js
import http from "k6/http";
import { check, sleep, group } from "k6";
import { Counter } from "k6/metrics";

// Track failed requests explicitly
export const failedRequests = new Counter("failed_requests");

// Define test stages (load pattern)
export const options = {
  stages: [
    { duration: "5s", target: 5 },   // ramp up to 5 VUs
    { duration: "20s", target: 10 }, // steady 10 VUs
    { duration: "5s", target: 0 },   // ramp down
  ],
  thresholds: {
    http_req_duration: ["p(95)<500"], // 95% of requests under 500ms
    http_req_failed: ["rate<0.05"],   // <5% failure rate allowed
  },
};

// Base URL of your API (use full accessible URL if GitHub Actions runs this)
const BASE_URL = "http:/3.132.157.35:8080/api";

// Login credentials
const credentials = {
  Email: "harvey@lna.com",
  Password: "lansa",
};

// HTTP headers
const params = {
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
};

// Main test logic
export default function () {
  group("User Login Test", function () {
    const res = http.post(`${BASE_URL}/login`, JSON.stringify(credentials), params);

    const ok = check(res, {
      "status is 2xx or 3xx": (r) => r.status >= 200 && r.status < 400,
    });

    if (!ok) {
      failedRequests.add(1);
      console.error(`❌ Request failed: ${res.status} - ${res.body}`);
    }
  });

  sleep(1); // short delay between requests
}

